version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    environment:
      - PORT=80
  frontend-react-docker:
    stdin_open: true
    build:
      context: .
      args:
        NODE_ENV: development
      dockerfile: Dockerfile
    # volumes is the way to sync local code, data to the container
    volumes:
      - .:/app # `./` is current host folder, now is my Windows machines code -> WHEN CHANGE CODES -> it reflects to containers -> NO NEED TO REBUILD but ALSO NEED nodemon or webpack to compiling
      - /app/node_modules # need bind mount node_modules if updating libs
    environment:
      - NODE_ENV=development
    command: sh -c "npm run build && npm start"
