version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - PORT=8080
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  frontend-react-docker:
    stdin_open: true
    image: hieptqsocial/react-docker-boiderplate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
