version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
  frontend-react-docker:
    stdin_open: true
    build:
      context: .
      args:
        NODE_ENV: development
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "./:/app"
    environment:
      - NODE_ENV=development
