version: "3.8"
services:
  frontend-react-docker-prod:
    stdin_open: true
    image: hieptqsocial/react-docker-boiderplate
    # container_name: frontend-react-docker-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    deploy:
      replicas: 2
      restart_policy:
        condition: any
      update_config:
        parallelism: 1 #number of container update at a time
        delay: 15s
    ports:
      - "80:80" # [learn] can use 3001:80 then use localhost:3001
    environment:
      - NODE_ENV=production
