version: "3.8"
services:
  frontend-react-docker-prod:
    stdin_open: true
    container_name: frontend-react-docker-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
