version: "3.8"
services:
  frontend:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "./:/app"
    environment:
      - NODE_ENV=development
