version: "3.8"
services:
  nginx:
    ports:
      - "80:80"
  frontend-react-docker:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm build:prod
