version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - PORT=80

  frontend-react-docker:
    stdin_open: true
    image: hieptqsocial/react-docker-boiderplate
    build:
      context: .
      dockerfile: Dockerfile
    # [learn] map outside port 80 to 3000 of container
    ports:
      - "80:3000"
